baseURL: https://cash-conscious.com/
languageCode: en-us
title: Cash Conscious
theme: "PaperMod"
googleAnalytics: G-REJQCCW23V
env: production

menu:
    main:
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 10
      - identifier: archives
        name: Archives
        url: /archives/
        weight: 20


params:
    defaultTheme: dark
    disableThemeToggle: true
    homeInfoParams:
        Title: "Hello there. 👋"
        Content: Welcome to Cash Conscious, your go-to source for personal finance tips, tricks and strategies. From budgeting and saving to investing and managing debt, we'll help you take control of your finances and achieve financial freedom. 
